### ISSUE TITLE
When using GeometryOperation.PROJ compilation issue

### ISSUE THREAD

**Issue by fxprunayre** [talend-spatial/workspace-metadata-crawler#43]
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	org.opengis.referencing.crs.CoordinateReferenceSystem cannot be resolved to a type
	org.opengis.referencing.crs.CoordinateReferenceSystem cannot be resolved to a type
	org.opengis.referencing.operation.MathTransform cannot be resolved to a type
	org.geotools.referencing.CRS cannot be resolved to a type
	org.geotools.referencing.CRS cannot be resolved to a type
	org.geotools.referencing.CRS cannot be resolved to a type

	at routines.GeometryOperation.PROJ(GeometryOperation.java:147)
	at test.scan_vector_0_1.scan_vector.sOGRInfoInput_2Process(scan_vector.java:19294)
	at test.scan_vector_0_1.scan_vector.tSetGlobalVar_1Process(scan_vector.java:4888)
	at test.scan_vector_0_1.scan_vector.sOGRInfoInput_1Process(scan_vector.java:4498)
	at test.scan_vector_0_1.scan_vector.tWarn_1Process(scan_vector.java:3429)
	at test.scan_vector_0_1.scan_vector.tLibraryLoad_1Process(scan_vector.java:3205)
	at test.scan_vector_0_1.scan_vector.tLibraryLoad_2Process(scan_vector.java:3008)
	at test.scan_vector_0_1.scan_vector.tLibraryLoad_3Process(scan_vector.java:2819)
	at test.scan_vector_0_1.scan_vector.runJobInTOS(scan_vector.java:33296)
	at test.scan_vector_0_1.scan_vector.main(scan_vector.java:32407)
```

Not sure why this is not resolved.

Using the `sProj` is a workaround for that issue. 

In `scan_vector`, `computeProperties`,

![image](https://user-images.githubusercontent.com/1701393/73279119-e9463080-41ec-11ea-8edc-bbdc8da577a5.png)

 set `var1` and `var2` to null solve the issue (those variables are not used).

![image](https://user-images.githubusercontent.com/1701393/73279084-daf81480-41ec-11ea-8d50-a4263b02a9b5.png)

**Comment by fxprunayre** [comment]
Issue fixed in https://github.com/talend-spatial/workspace-metadata-crawler/tree/7.x by not using the routine for now.
