### ISSUE TITLE
Error Failed to decode CRS when running job

### ISSUE THREAD

**Issue by fxprunayre** [talend-spatial/workspace-metadata-crawler#46]
* Error is 
```
Failed to decode CRS. Error message is: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)

```

**Comment by fxprunayre** [comment]
* Fix: You're probably using Java 11+. Use Java 8. Start Talend with Java 8 as default, or go to preference and switch to Java 8
